# Generated by Django 5.2 on 2025-05-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="person",
            name="unique_person_name_password",
        ),
        migrations.AlterField(
            model_name="person",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="person",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Feminine")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("username", "email"), name="unique_person_username_email"
            ),
        ),
    ]
